services:
  oracle:
    build:
      dockerfile: ./Dockerfile.oracle
    image: "ghcr.io/matevz/rofl-price-oracle"
    platform: linux/amd64
    entrypoint: /bin/sh -c 'python main.py --address "${ADDRESS}" --price-feed-address "${PRICE_FEED_ADDRESS}" --network ${NETWORK} --pair ${PAIR} --fetch-period $FETCH_PERIOD --submit-period $SUBMIT_PERIOD --api-key="${API_KEY}"'
    restart: on-failure
    environment:
      - ADDRESS=${ADDRESS}
      - PRICE_FEED_ADDRESS=${PRICE_FEED_ADDRESS}
      - NETWORK=${NETWORK:-sapphire-testnet}
      - PAIR=${PAIR:-bitstamp.net/btc/usd}
      - FETCH_PERIOD=${FETCH_PERIOD:-10}
      - SUBMIT_PERIOD=${SUBMIT_PERIOD:-60}
      - API_KEY=${API_KEY}
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock

