FROM ghcr.io/foundry-rs/foundry:latest AS contracts-build
COPY --chown=foundry ./contracts /contracts
RUN cd /contracts && forge build

FROM python:alpine3.17
WORKDIR /oracle
COPY ./oracle /oracle
COPY --from=contracts-build /contracts /contracts
RUN apk update && apk add python3-dev gcc libc-dev
RUN pip install -r requirements.txt
ENTRYPOINT ["python", "main.py"]
